/* Each step is [screen name, page-side JS that puts that screen on screen].
   The capture runs AFTER the body, so a body advances to the screen it names. */
module.exports = [
  {
    page: "Page 1 — New Captain onboarding",
    steps: [
      ["1.01 Login",                 ``],
      ["1.02 OTP entry",             `type("phone","7004301290"); click("go-otp");`],
      ["1.03 Role selection",        `for(let i=0;i<6;i++){const c=sel('.otp-cell[data-i="'+i+'"]');c.value="0";c.dispatchEvent(new Event("input",{bubbles:true}));} click("verify-otp");`],
      ["1.04 Personal details",      `clickSel('[data-pick="FM"]');`],
      ["1.05 Personal details filled", `type("pd-name","Karan Verma"); type("pd-alt","9876543210"); type("pd-email","karan.verma@gmail.com"); click("pd-verify-email"); type("pd-email-otp","000000"); click("pd-email-otp-go"); type("pd-pin","560076"); click("pd-addpin"); click("pd-check"); clickSel('[data-selpin="560076"]');`],
      ["1.06 KYC · Aadhaar",         `click("pd-continue");`],
      ["1.07 KYC · Aadhaar OTP",     `type("kyc-aadhaar","123412341234"); click("kyc-aadhaar-go");`],
      ["1.08 KYC · Aadhaar verified",`type("kyc-aadhaar-otp","000000"); click("kyc-aadhaar-confirm");`],
      ["1.09 KYC · PAN",             `click("kyc-ack-aadhaar");`],
      ["1.10 KYC · PAN verified",    `type("kyc-pan","ABCDE1234F"); type("kyc-pan-father","Suresh Verma"); click("kyc-pan-go");`],
      ["1.11 KYC · Bank account",    `click("kyc-ack-pan");`],
      ["1.12 KYC · Bank verified",   `type("kyc-acc","123456789012"); type("kyc-ifsc","HDFC0001234"); click("kyc-bank-go");`],
      ["1.13 KYC · GST status",      `click("kyc-ack-bank");`],
      ["1.14 KYC · GSTIN entered",   `clickSel('[data-gstchoice="registered"]'); type("kyc-gstin","29ABCDE1234F1Z5");`],
      ["1.15 KYC · MSME optional",   `click("kyc-gst-go");`],
      ["1.16 KYC complete",          `click("kyc-msme-go");`],
      ["1.17 Hub details",           `click("kyc-continue");`],
      ["1.18 Hub details · vehicle picker", `type("hub-address","Plot 7, Bommasandra Industrial Area, Bengaluru"); type("hub-map","https://maps.google.com/?q=12.8156,77.6982"); type("hub-area","6500"); type("hub-manpower","18"); click("veh-toggle");`],
      ["1.19 Hub details complete",  `clickSel('#veh-list [data-veh="10MT_32FT"]');`],
      ["1.20 Hub submitted",         `click("hub-submit");`],
      ["1.21 Background verification", `click("hub-continue");`],
      ["1.22 Background verification passed", `api.actions.bgvSet("passed");`],
      ["1.23 Cluster Head review · waiting", `click("bgv-continue");`],
      ["1.24 Cluster Head review · approved", `api.actions.chSetCategory("standalone"); api.actions.chApprove("combined");`],
      ["1.25 Agreements",            `click("ch-continue");`],
      ["1.26 Agreements accepted",   `setCheck("ag-rate",true); api.actions.markAgreementRead(); setCheck("ag-service",true);`],
      ["1.27 Activation",            `click("ag-activate");`],
    ],
  },
  {
    page: "Page 2 — Existing Captain, new hub",
    steps: [
      ["2.01 Login switch · existing captain", `dev("as:existing");`],
      ["2.02 Captain Hub · my hubs", `login("7004301290");`],
      ["2.03 Captain Hub · profile", `click("hub-user");`],
      ["2.04 Captain Hub · hubs tab", `clickSel('[data-ptab="hubs"]');`],
      ["2.05 Add a hub · choices",   `click("hub-add");`],
      ["2.06 Add a hub · FM, new GSTIN", `clickSel('[data-addrole="FM"]'); clickSel('[data-choice="new"]'); type("addhub-gstin","29ZZABC1234F1Z5");`],
      ["2.07 Hub details · KYC carried over", `click("addhub-go");`],
      ["2.08 Hub details · vehicle picker", `type("hub-address","Shed 12, Peenya Industrial Area, Bengaluru"); type("hub-map","https://maps.google.com/?q=13.0280,77.5190"); type("hub-area","5200"); type("hub-manpower","14"); click("veh-toggle");`],
      ["2.09 Hub details complete",  `clickSel('#veh-list [data-veh="7MT_20FT"]');`],
      ["2.10 Hub submitted",         `click("hub-submit");`],
      ["2.11 Cluster Head review · waiting", `click("hub-continue");`],
      ["2.12 Cluster Head review · approved", `api.actions.chSetCategory("standalone"); api.actions.chApprove("combined");`],
      ["2.13 Agreements",            `click("ch-continue");`],
      ["2.14 Agreements accepted",   `setCheck("ag-rate",true); api.actions.markAgreementRead(); setCheck("ag-service",true);`],
      ["2.15 Activation",            `click("ag-activate");`],
      ["2.16 Captain Hub · four hubs", `api.actions.openPanel(); api.actions.panelNav("hubs");`],
    ],
  },
  {
    page: "Page 3 — Admin login flows",
    steps: [
      ["3.01 Login switch · admin",   `dev("as:admin");`],
      ["3.02 Admin role picker",      `login("9876543210");`],
      ["3.03 AM · my requests",       `clickSel('[data-aprole="am"]');`],
      ["3.04 AM · infra checklist",   `clickSel('[data-apopen="OBD-78222"]');`],
      ["3.05 AM · infra checklist passed", `api.config.AM_GATES.forEach(g=>api.actions.amGate(g.id,"yes")); clickSel('[data-vehreview="yes"]');`],
      ["3.06 AM · carting design",    `click("am-to-design");`],
      ["3.07 AM · carting design · invalid code", `type("am-fmsc","SSY"); api.actions.designField("onboarding","split"); type("am-fmcds","KRM, ZZZ"); click("am-design-validate");`],
      ["3.08 AM · carting design validated", `type("am-fmcds","KRM, HSR"); click("am-design-validate");`],
      ["3.09 AM · carting design sent", `click("am-design-send"); click("am-to-design");`],
      ["3.10 AM · rate card",         `click("am-to-rate");`],
      ["3.11 AM · rate card within ceiling", `api.actions.amCategory("standalone"); api.actions.chSlabField(0,"rate","4.50"); api.actions.amRateField("touchpoint","5.00");`],
      ["3.12 AM · rate card above ceiling", `api.actions.chSlabField(0,"rate","6.20");`],
      ["3.13 Central Admin · design approvals", `api.actions.adminSwitchRole(); clickSel('[data-aprole="central"]'); clickSel('[data-aptab="design"]');`],
      ["3.14 Central Admin · design alignment", `clickSel('[data-apopen="OBD-78222"]');`],
      ["3.15 CH · my requests",       `click("ap-back"); api.actions.adminSwitchRole(); clickSel('[data-aprole="ch"]');`],
      ["3.16 CH · review within ceiling", `clickSel('[data-apopen="OBD-78219"]');`],
      ["3.17 CH · review above ceiling", `click("ap-back"); clickSel('[data-apopen="OBD-78255"]');`],
      ["3.18 ZH · pendency monitor",  `api.actions.adminSwitchRole(); clickSel('[data-aprole="zh"]');`],
      ["3.19 ZH · CH pendency",       `clickSel('[data-aptab="ch"]');`],
      ["3.20 ZH · request status",    `clickSel('[data-apopen="OBD-78219"]');`],
      ["3.21 Central Admin · queue",  `api.actions.adminSwitchRole(); clickSel('[data-aprole="ch"]'); api.actions.adminOpen("OBD-78255"); api.actions.chRate(4); click("ap-central"); api.actions.adminSwitchRole(); clickSel('[data-aprole="central"]');`],
      ["3.22 Central Admin · rate card approval", `clickSel('[data-apopen="OBD-78255"]');`],
    ],
  },
];
